#随机端口
server:
  port: 1429
#:注册服务至注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1410/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 60 #没过60秒给注册中心发送心跳
    lease-expiration-duration-in-seconds: 120 #超过120秒没发送心跳，让注册中心删除实例
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#数据源
spring:
  application:
    name: danju-data-Sql
  datasource:
    url: jdbc:mysql://localhost:3306/lib_danju?characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    datasource: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernare:
        dialect: org.hibernate.dialect.MySQL5Dialect